import Sidebar from "@/components/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex`}>
        <main className="p-16">
          <h1 className="text-4xl font-bold text-primary-content uppercase text-center">
            Monitoring Sparepart
          </h1>
          {children}
        </main>
      </body>
    </html>
  );
}
